#pragma once
#include <cstdint>   // REQUIRED for uintptr_t

namespace PS
{
    // NFS Pro Street - ReShade Pre FENg Hook
#ifndef HAS_DAL
#define HAS_DAL
#endif
#ifndef NFS_MULTITHREAD
#define NFS_MULTITHREAD
#endif
constexpr uintptr_t FEMANAGER_RENDER_HOOKADDR1 = 0x004B076A;
constexpr uintptr_t NFSUC_EXIT1 = 0x004B0774;
constexpr uintptr_t NFSUC_EXIT2 = 0x4B081C;
constexpr uintptr_t NFS_D3D9_DEVICE_ADDRESS = 0x00AC6ED4;
constexpr uintptr_t DRAW_FENG_BOOL_ADDR = 0x00A52AD8; 
//#define DRAW_FENG_BOOL_ADDR 0x4B1BB9 // in actual code...

constexpr uintptr_t SIM_SETSTREAM_ADDR = 0x004CF3F0;
constexpr uintptr_t WCOLMGR_GETWORLDHEIGHT_ADDR = 0x007AC4F0;
constexpr uintptr_t PLAYER_LISTABLESET_ADDR = 0x00ACE444;
constexpr uintptr_t MAINSERVICE_HOOK_ADDR = 0x006DB100;
constexpr uintptr_t SAVEHOTPOS_ADDR = 0x00AEB6A8;
constexpr uintptr_t LOADHOTPOS_ADDR = 0x00AEB6AC;

constexpr uintptr_t CHANGEPLAYERVEHICLE_ADDR = 0x00AEB6A0;

constexpr uintptr_t EXITGAMEFLAG_ADDR = 0x00ABAE68;
constexpr uintptr_t GAMEFLOWMGR_ADDR = 0x00ABB4F0;
constexpr uintptr_t GAMEFLOWMGR_STATUS_ADDR = 0xABB510;
constexpr uintptr_t GAMEFLOWMGR_UNLOADFE_ADDR = 0x006D3290;
constexpr uintptr_t GAMEFLOWMGR_UNLOADTRACK_ADDR = 0x006DBC60;
constexpr uintptr_t GAMEFLOWMGR_LOADREGION_ADDR = 0x006DBC10;
constexpr uintptr_t SKIPFE_ADDR = 0x00BFBC08;
constexpr uintptr_t SKIPFETRACKNUM_ADDR = 0x00A835D8;
constexpr uintptr_t SKIPFETRACKNUM_ADDR2 = 0x00A9D974;
constexpr uintptr_t DEFAULT_TRACK_NUM = 6000;
constexpr uintptr_t STARTSKIPFERACE_ADDR = 0x0074EFA0;

constexpr uintptr_t SKIPFE_NUMAICARS_ADDR = 0x00BFBC18;
constexpr uintptr_t SKIPFE_TRACKDIRECTION_ADDR = 0x00BFBC14;
constexpr uintptr_t SKIPFE_TRAFFICDENSITY_ADDR = 0x00BFBC24;
constexpr uintptr_t SKIPFE_TRAFFICONCOMING_ADDR = 0x00A9D9B4;
constexpr uintptr_t SKIPFE_DISABLETRAFFIC_ADDR = 0x00BFBC21;
//#define SKIPFE_DRAGRACE_ADDR 0x00864FC0
//#define SKIPFE_DRIFTRACE_ADDR 0x00864FC4
constexpr uintptr_t SKIPFE_P2P_ADDR = 0x00BFBC22;
constexpr uintptr_t SKIPFE_NUMPLAYERCARS_ADDR = 0x00A9D9AC;
constexpr uintptr_t SKIPFE_NUMLAPS_ADDR = 0x00A9D9B0;
constexpr uintptr_t SKIPFE_RACETYPE_ADDR = 0x00BFBC23;
constexpr uintptr_t SKIPFE_DIFFICULTY_ADDR = 0x00A9D9B8;

constexpr uintptr_t SKIPFE_PLAYERPERFORMANCE_ADDR = 0x00A9D994;
constexpr uintptr_t SKIPFE_NUMPLAYERSCREENS_ADDR = 0x00A9D9E4;
constexpr uintptr_t SKIPFE_RACEID_ADDR = 0x00A9D978;
constexpr uintptr_t SKIPFE_PLAYERCAR_ADDR = 0x00A9D97C;
constexpr uintptr_t SKIPFE_PLAYERCAR_DEHARDCODE_PATCH_ADDR = 0x004D4B41;
constexpr uintptr_t SKIPFE_PLAYERCAR2_ADDR = 0x00A9D984;
constexpr uintptr_t SKIPFE_PLAYERCAR3_ADDR = 0x00A9D988;
constexpr uintptr_t SKIPFE_PLAYERCAR4_ADDR = 0x00A9D98C;
//#define SKIPFE_OPPONENTPRESETRIDE_ADDR 0x008F86B0
constexpr uintptr_t SKIPFE_DISABLECOPS_ADDR = 0x00A9D59A;
constexpr uintptr_t SKIPFE_MAXCOPS_ADDR = 0x00BFBC1C;
constexpr uintptr_t SKIPFE_HELICOPTER_ADDR = 0x00BFBC20;

// New ProStreet stuff (other than 4 player support)
constexpr uintptr_t SKIPFE_TURBOSFX_ADDR = 0x00A9D980;
constexpr uintptr_t SKIPFE_FORCEHUBSELECTIONSET_ADDR = 0x00A9D998;
constexpr uintptr_t SKIPFE_FORCERACESELECTIONSET_ADDR = 0x00A9D998;
constexpr uintptr_t SKIPFE_FORCENIS_ADDR = 0x00A9D9A0;
constexpr uintptr_t SKIPFE_FORCENISCONTEXT_ADDR = 0x00A9D9A4;
constexpr uintptr_t SKIPFE_TRACTIONCONTROLLEVEL_ADDR = 0x00A9D9CC;
constexpr uintptr_t SKIPFE_STABILITYCONTROLLEVEL_ADDR = 0x00A9D9D0;
constexpr uintptr_t SKIPFE_ANTILOCKBRAKESLEVEL_ADDR = 0x00A9D9D4;
constexpr uintptr_t SKIPFE_DRIFTASSISTLEVEL_ADDR = 0x00A9D9D8;
constexpr uintptr_t SKIPFE_RACELINEASSISTLEVEL_ADDR = 0x00A9D9DC;
constexpr uintptr_t SKIPFE_BRAKINGASSISTLEVEL_ADDR = 0x00A9D9E0;
constexpr uintptr_t SKIPFE_TRANSMISSIONSETUP_ADDR = 0x00A9D9E8;
constexpr uintptr_t SKIPFE_ENABLEDEBUGACTIVITY_ADDR = 0x00BFBC2C;
constexpr uintptr_t SKIPFE_PRACTICEMODE_ADDR = 0x00BFBC2F;
constexpr uintptr_t SKIPFE_DISABLESMOKE_ADDR = 0x00BFBC38;
constexpr uintptr_t SKIPFE_SLOTCARRACE_ADDR = 0x00BFBC3A;
constexpr uintptr_t SKIPFE_BOOTFLOW_ADDR = 0x00BFBC41;

//#define AUGMENTEDDRIFT_ADDR 0x00BFBC39
constexpr uintptr_t SMARTLOOKAHEADCAMERA_ADDR = 0x00BFBC39;
//#define FORCEFAKEBOSS_ADDR 0x00A9E66C

inline const char* DEFAULT_PLAYERCAR = "350z_track";
inline const char* DEFAULT_PLAYER2CAR = "350z_track";
inline const char* DEFAULT_PLAYER3CAR = "350z_track";
inline const char* DEFAULT_PLAYER4CAR = "350z_track";

constexpr uintptr_t UNLOCKALLTHINGS_ADDR = 0x00BFBC5B;
constexpr uintptr_t SKIPCAREERINTRO_ADDR = 0x00BFBC6C;
//#define SKIPDDAYRACES_ADDR 0x00A9E6C2
constexpr uintptr_t SHOWALLCARSINFE_ADDR = 0x00BFBC6E;
constexpr uintptr_t CARGUYSCAMERA_ADDR = 0x00BFBC6F;

constexpr uintptr_t DOSCREENPRINTF_ADDR = 0x00BFBC70;

// Precipitation memory addresses (NFS ProStreet)
constexpr uintptr_t RAIN_CF_INTENSITY_ADDR = 0x00FEB1D4;
constexpr uintptr_t RAIN_DROP_OFFSET_ADDR = 0x00FEB1C8;
constexpr uintptr_t RAIN_DROP_ALPHA_ADDR = 0x00FEB1D0;
constexpr uintptr_t FOG_SKY_FALLOFF_ADDR = 0x00FEB198;
constexpr uintptr_t RAIN_PARAM_A_ADDR = 0x00FEB190;
constexpr uintptr_t FOG_BLEND_PARAM_ADDR = 0x00FEB1A0;

//#define DISABLECOPS_ADDR 0x00A83A50
constexpr uintptr_t CAMERADEBUGWATCHCAR_ADDR = 0x00AB4961;
constexpr uintptr_t MTOGGLECAR_ADDR = 0x00AB499C;
constexpr uintptr_t MTOGGLECARLIST_ADDR = 0x00AB49A0;
constexpr uintptr_t CAMERA_SETACTION_ADDR = 0x006494B0;
constexpr uintptr_t CAMERA_UPDATE_ADDR = 0x0064B940;

constexpr uintptr_t EVIEW_LIST_HEAD_PTR = 0x00A79B44;     // Example: global pointer to head of EViewNode list
constexpr uintptr_t NODE_MATRIX_OFFSET =  0x40;           // Offset of viewMatrix within EViewNode
constexpr uintptr_t GET_VISIBLE_STATE_SB_ADDR = 0x006FF730;

constexpr uintptr_t CAMERA_GETANCHOR_ADDR = 0x00845810;
constexpr uintptr_t GET_GAME_CAMERA_MOVER_ADDR = 0x00401F60;

constexpr uintptr_t CARLIST_TYPE_AIRACER = 3;
constexpr uintptr_t CARLIST_TYPE_COP = 4;
constexpr uintptr_t CARLIST_TYPE_TRAFFIC = 5;

constexpr uintptr_t GETSIMABLE_OFFSET = 0x4;
constexpr uintptr_t UTL_ILIST_FIND_ADDR = 0x004614B0;

constexpr uintptr_t AI_RANDOMTURNS_ADDR = 0x00AEE853;

// car flip stuff
constexpr uintptr_t VEHICLE_LISTABLESET_ADDR = 0x00ACE144;
constexpr uintptr_t IRIGIDBODY_HANDLE_ADDR = 0x00402280;
constexpr uintptr_t RB_GETMATRIX4_OFFSET = 0x40;
constexpr uintptr_t RB_SETORIENTATION_OFFSET = 0x70;

// infinite NOS
constexpr uintptr_t INFINITENOS_CAVE_ADDR = 0x00488D19;

// AI Control toggle
constexpr uintptr_t AICONTROL_CAVE_ADDR = 0x41D296;
constexpr uintptr_t AICONTROL_CAVE_EXIT = 0x0041D29C;
constexpr uintptr_t UPDATEWRONGWAY_ADDR = 0x0041CEC0;

constexpr uintptr_t PRECULLERMODE_ADDR = 0x00A9D9C8;

constexpr uintptr_t FENG_QUEUEPACKAGEPOP_ADDR = 0x0059F160;
constexpr uintptr_t FENG_QUEUEPACKAGEPUSH_ADDR = 0x005AC340;
constexpr uintptr_t FENG_QUEUEPACKAGESWITCH_ADDR = FENG_QUEUEPACKAGEPUSH_ADDR;

constexpr uintptr_t GAMENOTIFYRACEFINISHED_ADDR = 0x006E9D00;
constexpr uintptr_t GAMEENTERPOSTRACEFLOW_ADDR = 0x006E9EA0;

//#define APPLYVISUALLOOK_ADDR 0x00A65394
//#define DRAWWORLD_ADDR 0x00A63E0C
constexpr uintptr_t DRAWWORLD_CAVE_ADDR = 0x004BD56D;
constexpr uintptr_t DRAWWORLD_CAVE_TRUE_EXIT = 0x004BD57B;
constexpr uintptr_t DRAWWORLD_CAVE_FALSE_EXIT = 0x004BD732;
constexpr uintptr_t DRAWCARS_ADDR = 0x00A79CDC;
constexpr uintptr_t DRAWCARSHADOWS_ADDR = 0x00A79CE4;
//#define GAMESPEED_ADDR 0x00A712AC
constexpr uintptr_t GAMESPEED_CAVE_ADDR = 0x004D5245;
constexpr uintptr_t GAMESPEED_CAVE_EXIT = 0x4D5277;

constexpr uintptr_t PUSHMOVIE_ADDR = 0x005AC600;
constexpr uintptr_t ISMOVIEPLAYING_ADDR = 0x00AB27E0;

// player cash & DAL stuff
constexpr uintptr_t FEMANAGER_INSTANCE_ADDR = 0x00AB27D8;
//#define USERPROFILE_POINTER (*(int*)(*(int*)((*(int*)FEMANAGER_INSTANCE_ADDR) + 0xD4)))
#define USERPROFILE_POINTER (*(int*)0x00AB0EAC)
const uintptr_t FECAREER_POINTER = (*(int*)0x00AB0EA8);
#define PLAYERCASH_POINTER (FECAREER_POINTER + 0x1E0)
#define CURRENTBIN_POINTER (FECAREER_POINTER + 0x1E4)
    
//#define PLAYERREP_POINTER (USERPROFILE_POINTER + 0x24334)
//#define CREWNAME_POINTER (USERPROFILE_POINTER + 0x24314)
//#define PROFILENAME_POINTER (USERPROFILE_POINTER + 0x10)
//#define CAR_FEPOSITION_POINTER (USERPROFILE_POINTER + 0x2946A)
//#define CAR_FEPOSITION_COUNT 10
// DAL options
#define MASTERVOL_POINTER  (USERPROFILE_POINTER + 0x90954)
#define SPEECHVOL_POINTER  (USERPROFILE_POINTER + 0x90958)
#define FEMUSICVOL_POINTER  (USERPROFILE_POINTER + 0x9095C)
#define IGMUSICVOL_POINTER  (USERPROFILE_POINTER + 0x90960)
#define SOUNDEFFECTSVOL_POINTER  (USERPROFILE_POINTER + 0x90964)
#define ENGINEVOL_POINTER  (USERPROFILE_POINTER + 0x90968)
#define CARVOL_POINTER  (USERPROFILE_POINTER + 0x9096C)
#define AMBIENTVOL_POINTER  (USERPROFILE_POINTER + 0x90970)
#define SPEEDVOL_POINTER  (USERPROFILE_POINTER + 0x90974)

#define HIGHLIGHTCAM_POINTER (USERPROFILE_POINTER + 0x90938)
    //#define JUMPCAM_POINTER (USERPROFILE_POINTER + 0x24219)
#define TIMEOFDAY_POINTER (USERPROFILE_POINTER + 0x908E0)
    //#define DAMAGEON_POINTER (USERPROFILE_POINTER + 0x2420B)
    //#define AUTOSAVEON_POINTER (USERPROFILE_POINTER + 0x24208)

#define FESCALE_POINTER (USERPROFILE_POINTER + 0x908DC)
#define WIDESCREEN_POINTER (USERPROFILE_POINTER + 0x90925)

//#define FEPOSITION_POINTER (USERPROFILE_POINTER + 0x24279)
//#define FELAPINFO_POINTER (USERPROFILE_POINTER + 0x2427A)
//#define FESCORE_POINTER (USERPROFILE_POINTER + 0x2427B)
//#define FELEADERBOARD_POINTER (USERPROFILE_POINTER + 0x2427D)
//#define FECREWINFO_POINTER (USERPROFILE_POINTER + 0x2427E)
//#define FETRANSMISSIONPROMPT_POINTER (USERPROFILE_POINTER + 0x2427F)
//#define FERVM_POINTER (USERPROFILE_POINTER + 0x24209)
//#define FEPIP_POINTER (USERPROFILE_POINTER + 0x2420A)
//#define SPEEDOUNIT_POINTER (USERPROFILE_POINTER + 0x2420C)

//#define DRIVEWITHANALOG_POINTER (USERPROFILE_POINTER + 0x24280)
//#define INPUT_SENSITIVITYSETTING_POINTER (USERPROFILE_POINTER + 0x24284)
//#define RUMBLEON_POINTER (USERPROFILE_POINTER + 0x2427C)
//#define PCPADIDX_POINTER (USERPROFILE_POINTER + 0x242D0)
//#define PCDEVTYPE_POINTER (USERPROFILE_POINTER + 0x242D4)

//#define BRIGHTNESS_POINTER (USERPROFILE_POINTER + 0x241F0)

    
constexpr uintptr_t EViewListHeadPtr = EVIEW_LIST_HEAD_PTR;
    
#define GRACESTATUS_ADDR 0x00AB9D7C

    void ReShade_EntryPoint();
    void __stdcall MainService_Hook();
    void ToggleAIControlCave();
    void InfiniteNOSCave();
    void DrawWorldCave();
    void GameSpeedCave();
}